def get_account_info():
    return {
        "login": 12345678,  # Account number (int)
        "trade_servers": "MetaQuotes-Demo",  # Trading server name (str)
        "name": "Yousuf Ahamad",  # Account holder's name (str)
        "server": "MetaQuotes-Demo",  # Server name (str)
        "currency": "USD",  # Account currency (str, e.g., 'USD', 'EUR')
        "balance": 10000.0,  # Current balance (float)
        "equity": 10250.75,  # Current equity (balance + floating P/L) (float)
        "margin": 350.40,  # Used margin (float)
        "margin_free": 9650.35,  # Free margin (float)
        "margin_level": 2924.15,  # Margin level in % (float, can be None if no positions)
        "margin_so_call": 100.0,  # Stop Out level for margin call (%) (float)
        "margin_so_so": 50.0,  # Stop Out level (%) (float)
        "credit": 0.0,  # Credit amount (float)
        "profit": 250.75,  # Floating profit/loss (float)
        "storage": 0.0,  # Swap storage (float)
        "commission": 0.0,  # Commission paid (float)
        "assets": 0.0,  # Assets value (for some account types) (float)
        "liabilities": 0.0,  # Liabilities (float)
        "blocked_commission": 0.0,  # Blocked commission (float)
        "type": 1,  # Account type (int: 1=Real, 2=Demo, etc.)
        "leverage": 500,  # Account leverage (int, e.g., 100, 500, 1000)
        "trade_allowed": True,  # Is trading allowed (bool)
        "trade_expert": True,  # Are Expert Advisors allowed (bool)
        "limit_orders": 100,  # Maximum number of pending orders (int)
        "margin_mode": 0,  # Margin calculation mode (int)
        "currency_digits": 2,  # Number of digits after decimal in currency (int)
    }
